### ISSUE TITLE
Exception when processing latest LCL for Austria

### ISSUE THREAD

**Issue by mvglasow** [ChristopheJacquet/RdsSurveyor#21]
When importing the latest LCL for Austria (version 3.2), I get the following error:

```
Processing table Names from file /home/michael/workspaces/rds-surveyor/lt/at/NAMES.DAT
Could not determine type for column OFFICIALNAME:
java.sql.SQLException: Column not found: OFFICIALNAME
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCResultSet.findColumn(Unknown Source)
	at eu.jacquet80.rds.app.oda.tmc.TMC.getColumnTypes(TMC.java:1061)
	at eu.jacquet80.rds.app.oda.tmc.TMC.importTable(TMC.java:1085)
	at eu.jacquet80.rds.app.oda.tmc.TMC.readLocationTablesFromDir(TMC.java:1004)
	at eu.jacquet80.rds.app.oda.tmc.TMC.readLocationTables(TMC.java:817)
	at eu.jacquet80.rds.RDSSurveyor.main(RDSSurveyor.java:303)
Caused by: org.hsqldb.HsqlException: Column not found: OFFICIALNAME
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	... 7 more
java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: OFFICIALNAME
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source)
	at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source)
	at eu.jacquet80.rds.app.oda.tmc.TMC.importTable(TMC.java:1102)
	at eu.jacquet80.rds.app.oda.tmc.TMC.readLocationTablesFromDir(TMC.java:1004)
	at eu.jacquet80.rds.app.oda.tmc.TMC.readLocationTables(TMC.java:817)
	at eu.jacquet80.rds.RDSSurveyor.main(RDSSurveyor.java:303)
Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: OFFICIALNAME
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.ParserDQL.readSimpleColumnName(Unknown Source)
	at org.hsqldb.ParserDQL.readSimpleColumnNames(Unknown Source)
	at org.hsqldb.ParserDML.compileInsertStatement(Unknown Source)
	at org.hsqldb.ParserCommand.compilePart(Unknown Source)
	at org.hsqldb.ParserCommand.compileStatement(Unknown Source)
	at org.hsqldb.Session.compileStatement(Unknown Source)
	at org.hsqldb.StatementManager.compile(Unknown Source)
	at org.hsqldb.Session.execute(Unknown Source)
	... 6 more
```

The LCL claims compliance with TISA Approved Document Version 18 - TMC Location Table Exchange Format version 2.3 - 27-May-2014.

Looking at the LCL, `NAMES.DAT` has a column `OFFICIALNAME` which I have not seen in other LCLs so far (might have been added in a later version of the spec).

Working on a fix...

**Comment by mvglasow** [comment]
Closed with #22 .
